[workspace]
resolver = "2"
members = [
    "rust/orbit",
    "rust/orbitd",
    "rust/orbitctl",
    "rust/orbit-android",
    "rust/uniffi-bindgen",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
